#!/usr/bin/env python3
"""
Create a daily repository maintenance report.

The report captures lightweight, meaningful repository health data so that
automated commits represent real operational activity.
"""

from __future__ import annotations

import datetime as dt
import hashlib
import subprocess
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
REPORT_DIR = REPO_ROOT / "reports" / "daily-health"
REQUIREMENTS_FILE = REPO_ROOT / "requirements.txt"
SRC_DIR = REPO_ROOT / "src"


def run_git(command: list[str]) -> str:
    """Run a git command and return trimmed stdout."""
    result = subprocess.run(
        command,
        cwd=REPO_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def count_python_files(path: Path) -> int:
    if not path.exists():
        return 0
    return len(list(path.rglob("*.py")))


def file_sha256(path: Path) -> str:
    if not path.exists():
        return "missing"
    return hashlib.sha256(path.read_bytes()).hexdigest()


def build_report_content() -> str:
    today = dt.datetime.now(dt.UTC)
    date_text = today.strftime("%Y-%m-%d")
    timestamp = today.strftime("%Y-%m-%d %H:%M:%S UTC")

    last_commit = run_git(["git", "rev-parse", "--short", "HEAD"])
    commit_count = run_git(["git", "rev-list", "--count", "HEAD"])
    branch = run_git(["git", "rev-parse", "--abbrev-ref", "HEAD"])

    requirements_hash = file_sha256(REQUIREMENTS_FILE)
    python_file_count = count_python_files(SRC_DIR)

    return "\n".join(
        [
            f"# Daily Repository Health Report - {date_text}",
            "",
            f"- Generated at: {timestamp}",
            f"- Branch: {branch}",
            f"- Latest commit before report: {last_commit}",
            f"- Total commits in history: {commit_count}",
            f"- Python files in src/: {python_file_count}",
            f"- requirements.txt sha256: {requirements_hash}",
            "",
            "## Notes",
            "",
            "- This file is generated by CI to keep a traceable operational history.",
            "- If values changed unexpectedly, review recent commits and dependencies.",
            "",
        ]
    )


def main() -> None:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    today = dt.datetime.now(dt.UTC).strftime("%Y-%m-%d")
    report_file = REPORT_DIR / f"{today}.md"
    report_file.write_text(build_report_content(), encoding="utf-8")
    print(f"Wrote {report_file.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
